
pub fn test_board() -> crate::Board {
    use crate::Tile::{Hard, Empty};
    [
        [
            Hard(
                4,
            ),
            Hard(
                3,
            ),
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
            Hard(
                7,
            ),
            Empty,
        ],
        [
            Empty,
            Empty,
            Empty,
            Empty,
            Hard(
                9,
            ),
            Empty,
            Empty,
            Empty,
            Empty,
        ],
        [
            Empty,
            Empty,
            Empty,
            Empty,
            Hard(
                1,
            ),
            Hard(
                6,
            ),
            Empty,
            Hard(
                2,
            ),
            Empty,
        ],
        [
            Hard(
                5,
            ),
            Hard(
                7,
            ),
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
            Hard(
                4,
            ),
        ],
        [
            Hard(
                8,
            ),
            Empty,
            Empty,
            Hard(
                6,
            ),
            Empty,
            Empty,
            Hard(
                9,
            ),
            Hard(
                5,
            ),
            Empty,
        ],
        [
            Empty,
            Empty,
            Empty,
            Hard(
                8,
            ),
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
        ],
        [
            Hard(
                1,
            ),
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
            Empty,
        ],
        [
            Empty,
            Empty,
            Empty,
            Empty,
            Hard(
                8,
            ),
            Hard(
                2,
            ),
            Empty,
            Empty,
            Empty,
        ],
        [
            Empty,
            Empty,
            Hard(
                3,
            ),
            Hard(
                9,
            ),
            Empty,
            Empty,
            Hard(
                4,
            ),
            Hard(
                6,
            ),
            Hard(
                5,
            ),
        ],
    ]
}